# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HMAlerts.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HMAlerts.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eHMAlerts.proto\"o\n\x07hmAlert\x12\x13\n\x0bhm_alert_id\x18\x01 \x01(\t\x12\x12\n\nhm_message\x18\x02 \x01(\t\x12\x11\n\thm_status\x18\x03 \x01(\t\x12\x16\n\x0ehm_suspend_for\x18\x04 \x01(\x05\x12\x10\n\x08hm_agent\x18\x05 \x01(\t\"\x1d\n\nhmResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2\x81\x02\n\x0c\x41lertManager\x12#\n\x08setAlert\x12\x08.hmAlert\x1a\x0b.hmResponse\"\x00\x12\'\n\x0csuspendAlert\x12\x08.hmAlert\x1a\x0b.hmResponse\"\x00\x12)\n\x0eunsuspendAlert\x12\x08.hmAlert\x1a\x0b.hmResponse\"\x00\x12\'\n\x0c\x64ismissAlert\x12\x08.hmAlert\x1a\x0b.hmResponse\"\x00\x12*\n\x0freactivateAlert\x12\x08.hmAlert\x1a\x0b.hmResponse\"\x00\x12#\n\x08getAlert\x12\x08.hmAlert\x1a\x0b.hmResponse\"\x00\x62\x06proto3')
)




_HMALERT = _descriptor.Descriptor(
  name='hmAlert',
  full_name='hmAlert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hm_alert_id', full_name='hmAlert.hm_alert_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hm_message', full_name='hmAlert.hm_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hm_status', full_name='hmAlert.hm_status', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hm_suspend_for', full_name='hmAlert.hm_suspend_for', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hm_agent', full_name='hmAlert.hm_agent', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=129,
)


_HMRESPONSE = _descriptor.Descriptor(
  name='hmResponse',
  full_name='hmResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='hmResponse.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=160,
)

DESCRIPTOR.message_types_by_name['hmAlert'] = _HMALERT
DESCRIPTOR.message_types_by_name['hmResponse'] = _HMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

hmAlert = _reflection.GeneratedProtocolMessageType('hmAlert', (_message.Message,), dict(
  DESCRIPTOR = _HMALERT,
  __module__ = 'HMAlerts_pb2'
  # @@protoc_insertion_point(class_scope:hmAlert)
  ))
_sym_db.RegisterMessage(hmAlert)

hmResponse = _reflection.GeneratedProtocolMessageType('hmResponse', (_message.Message,), dict(
  DESCRIPTOR = _HMRESPONSE,
  __module__ = 'HMAlerts_pb2'
  # @@protoc_insertion_point(class_scope:hmResponse)
  ))
_sym_db.RegisterMessage(hmResponse)



_ALERTMANAGER = _descriptor.ServiceDescriptor(
  name='AlertManager',
  full_name='AlertManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=163,
  serialized_end=420,
  methods=[
  _descriptor.MethodDescriptor(
    name='setAlert',
    full_name='AlertManager.setAlert',
    index=0,
    containing_service=None,
    input_type=_HMALERT,
    output_type=_HMRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='suspendAlert',
    full_name='AlertManager.suspendAlert',
    index=1,
    containing_service=None,
    input_type=_HMALERT,
    output_type=_HMRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='unsuspendAlert',
    full_name='AlertManager.unsuspendAlert',
    index=2,
    containing_service=None,
    input_type=_HMALERT,
    output_type=_HMRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='dismissAlert',
    full_name='AlertManager.dismissAlert',
    index=3,
    containing_service=None,
    input_type=_HMALERT,
    output_type=_HMRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='reactivateAlert',
    full_name='AlertManager.reactivateAlert',
    index=4,
    containing_service=None,
    input_type=_HMALERT,
    output_type=_HMRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getAlert',
    full_name='AlertManager.getAlert',
    index=5,
    containing_service=None,
    input_type=_HMALERT,
    output_type=_HMRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALERTMANAGER)

DESCRIPTOR.services_by_name['AlertManager'] = _ALERTMANAGER

# @@protoc_insertion_point(module_scope)
